# docker-compose.yml (versão final simplificada)
version: '3.8'

services:
  backend:
    build:
      context: ./server
    container_name: fullstack-backend
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      POSTGRES_HOST: db
    depends_on:
      - db
    networks:
      - app-network
    # A linha 'command' foi removida, pois agora tudo é feito no Dockerfile

  frontend:
    build:
      context: ./client
      args:
        VITE_API_BASE_URL: http://localhost:3001/api
    container_name: fullstack-frontend
    restart: unless-stopped
    ports:
      - '5173:80'
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    container_name: fullstack-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: fullstack-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgadmin-data:
    driver: local